### ISSUE TITLE
ldiv! with cached lu factorization?

### ISSUE THREAD

**Issue by stevengj** [jbshannon/LocalPoly.jl#13]
I notice that your `_lpreg!` function, while it takes great care to use `mul!` to perform in-place multiplications, also does `β̂ = XWX\XWY`.   Why not cache `lu(XWX)` in your `LPModel`, and then use `ldiv!` with a preallocated output vector?

**Comment by jbshannon** [comment]
The contents of the matrices `X` and `W` are altered with the value `x₀` for each function call, so the factorization object would only be used once at each evaluation point. I can, however, do `ldiv!(β̂, lu!(XWX), XWY)`, which is slightly better than what I have.
